version: '3.5'

services:
  postgres:
    container_name: postgres-pdv
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pdv
    volumes:
      - ./data:/data/postgres
    ports:
      - '5432:5432'
